name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install and Build
      run: |
        npm install
        npm run-script build

  Dev_A:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Deploy to Dev A
      # uses: JamesIves/github-pages-deploy-action@releases/v3
      # with:
      #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BRANCH: gh-pages
      #   FOLDER: build
      run: echo "Demo for dev deploy"
  
  Dev_b:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Deploy to Dev B
      # uses: JamesIves/github-pages-deploy-action@releases/v3
      # with:
      #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BRANCH: gh-pages
      #   FOLDER: build
      run: echo "Demo for dev deploy"    

  Production:
    runs-on: ubuntu-latest
    needs: [Dev_A, Dev_B]
    steps:
    - name: Deploy to Prd
      # uses: JamesIves/github-pages-deploy-action@releases/v3
      # with:
      #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BRANCH: gh-pages
      #   FOLDER: build
      run: echo "Demo for prd deploy"    