name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install and Build
      run: |
        npm install
        npm run-script build

  Dev_A:
    runs-on: ubuntu-latest
    environment: Dev_A
    needs: Build
    steps:
    - name: Deploy to Dev A
      run: echo "Demo for dev deploy"
  
  Dev_B:
    runs-on: ubuntu-latest
    environment: Dev_B
    needs: Build
    steps:
    - name: Deploy to Dev B
      run: echo "Demo for dev deploy"    

  Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: [Dev_A, Dev_B]
    steps:
    - name: Deploy to Prd
      run: echo "Demo for prd deploy"    